theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Analyze EML Content
description: R code examples for analyzing metadata content
production_url: https://cgries.github.io/eml-content-analysis/
logo: /assets/img/edi-logo-svg.png
show_downloads: true
